# Generated by Django 5.0.1 on 2024-01-29 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='productivity',
        ),
        migrations.AddField(
            model_name='productivity',
            name='todo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='productivity', to='todo.todo'),
            preserve_default=False,
        ),
    ]
